- app/assets/stylesheets/core/layouts/modern/_footer.sass
> Fixed footer nav width for small screens

- app/assets/javascripts/lib/analytics/travel_insurance_omniture.js
> This PR must be tested and released in conjunction with Landing Page PR \ https://github.com/lonelyplanet/landing-pages/pull/311
Adding standard `js-` prefix to class where click tracking is needed. Changed `article--row` to `js-card` to be more specific and utilize a `js-` already being used.
> Proper usage of `js-` prefix on classes

- app/assets/stylesheets/core/layouts/modern/_breadcrumbs.sass
- app/views/components/navigation/_breadcrumbs.html.haml
Before:
After:
\+ fixed disappearing `/` in responsive default breadcrumbs (bug example from Waldorf's gallery):
> Tweaked footer breadcrumbs rwd

- app/assets/stylesheets/components/_left_nav.sass
> Trello issue: https://trello.com/c/6WkjO9OP/617-link-not-working-properly
The left nav links on The World view were navigating to another view before the JavaScript loaded.  I added the `.disabled` class so that users had the indication that they could not be clicked on.
Test this change with Waldorf pull request https://github.com/lonelyplanet/waldorf/pull/1794
> Adding a class to allow a left nav item to appear disabled

- app/assets/stylesheets/components/_tags.sass
- app/assets/stylesheets/core/_inputs.sass
- app/assets/stylesheets/core/_layout.sass
- app/assets/stylesheets/core/core_components/_accordion.sass
- app/assets/stylesheets/core/core_components/_card_layer.sass
- app/assets/stylesheets/core/core_components/_place_title.sass
- app/assets/stylesheets/core/layouts/legacy/_overrides.sass
- app/assets/stylesheets/core/layouts/modern/_ads.sass
- app/assets/stylesheets/core/layouts/modern/_cookie_compliance.sass
- app/assets/stylesheets/core/layouts/modern/_nav_flyout.sass
- app/assets/stylesheets/core/layouts/modern/_primary_nav.sass
- app/assets/stylesheets/core/layouts/modern/_responsive_nav.sass
- app/assets/stylesheets/core/layouts/modern/_shopping_cart.sass
- app/assets/stylesheets/core/layouts/modern/_user_feed.sass
- app/assets/stylesheets/core/utilities/_responsive.sass
- app/assets/stylesheets/sass/extends/lp_styles/_decoration.sass
- app/assets/stylesheets/widgets/_booking.sass
Removing all the instances of `.responsive` is a hairy task so taking it piece by piece. This is just for the primary nav.
The code is pretty tricky to review, though still worth a look, easiest might be to pull it down. To test, remove the `responsive` class from `body` in `responsive.html.haml`.
The responsive class will be removed finally once it's all been removed from the css.
In IE
Shop
> If remove responsive primary nav

- app/assets/stylesheets/sass/mixins/_responsive.sass
Add an option to output the styles for browsers that do not support media query styles.
For example, we would like to be able to apply the `width` and `display` to IE7/8 in addition to `wide-view` media query block.
```.group--highlight
+respond-to(wide-view, $fallback: true, $legacy: true)
width: 50%
display: block
> ability deliver media query styles to old browsers

- app/assets/javascripts/lib/components/datepicker.js
Consistently format labels for datepicker.
FROM
TO
> fix date format issue with datepicker label

- app/assets/stylesheets/core/core_components/_forms.sass
Before these were always 100% wide:
Just had to make shared attributes go first.
> Fix for `.field__label` & `.field__content` to be actually responsive

- app/assets/stylesheets/components/_poi_list.sass
The POI descriptions currently have a transparent background and they overlay the map itself.  It looks bad.  This fix adds `respond-to-legacy-support` to the `poi_list.sass` and places the description below the map.
* To check this PR open a hotel page in IE8 and check that the POIs descriptions are below the map.
> This makes the map POI in IE8 look better.

- app/assets/javascripts/lib/components/toggle_active.js
- spec/javascripts/fixtures/toggle_active.html
- spec/javascripts/lib/components/toggle_active_spec.js
- applied [yeoman](https://github.com/lonelyplanet/yeoman/blob/rizzo/javascript-component/templates/component.js) template
- removed listener (no need to use both context & listener at the same time?)
- events are now live within context (support dynamically added toggles - for ex. report form toggle in profile lightbox in Community)
> Tweaked toggleActive a bit

- app/assets/stylesheets/components/_banner.sass
- app/data/styleguide/herobanner_stubs.yml
> Fix the 'story behind the picture' feature in hero banners

- app/views/layouts/partials/inline_js/_require_js_config.html.haml
Adding a shim in require so ensure that jQuery is loaded before the deparam plugin loads.  Production was encountering a race condition issue where the deparam plugin was being loaded before jQuery itself was done being loaded.  This caused cascading errors to happen and all kinds of ugliness on the pages handled by Waldorf.
1. Check out branch and point Waldorf to local rizzo
1. Visit `http://localhost:8080/austria` and verify that ads load and no JavaScript errors are reported in the console. Specifically the `jQuery not defined` error that was happening in production.
> Adding shim for deparam plugin

- app/assets/javascripts/lib/core/nav_search.js
turns out it's "label", not "value".
> switched analytics label

- app/assets/javascripts/lib/components/poi_map.js
The container div has been places absolutely on the placeholder. An `mv--inline` class has been put on the container as of January 25th, this has caused events not fire on the placeholder.
https://github.com/lonelyplanet/rizzo/blame/5c329b314761290f7b61288e02e084e795c1023b/app/assets/stylesheets/core/utilities/_responsive.sass#L114
Simply changing where the events are bound to the container seems to resolve the issue.
> Fix issue with events  not working

- app/assets/javascripts/lib/components/range_slider.js
- app/views/components/forms/_range_slider.html.haml
- spec/javascripts/lib/components/range_slider_spec.js
- vendor/assets/javascripts/nouislider/jquery.nouislider.js
This PR adds the option of `snapDateAt` to the range_slider component, which is specified on the data property of the haml template as `snap_date_at`. 
If this option is provided, the range slider will snap to 24 unit steps rather than allowing the granularity of 1 unit at the value specified in `snap_date_at`.
The reasoning for this is to fix an issue where filters were allowing hour granularity, even though the labels for the filter were showing at the day level of granularity. This caused the UI to send values that would filter out TTD that would appear to the user to be within the selected range.
> Ds add snapto on range slider

- app/assets/stylesheets/core/core_components/_buttons.sass
`.btn--outline` is 2px higher than any other button.
Before:
After:
> Fix inconsistent button height bug

- app/views/layouts/responsive.html.haml
This PR allows apps to not use the blue bar (specifically for some BizDev projects).
**Example implementation:**
```
layout "responsive"
def index
@no_nav = true
render "mypage"
end
```
> added @no_nav check for apps that don't need nav bar

- app/assets/javascripts/lib/core/ad_sizes.js
- app/assets/javascripts/lib/core/ad_unit.js
Per Tim Daugherty, the ad unit at bottom on destinations needs to be 728x90 on desktop and 300x250 on mobile.  This adds the new size.
> Adding new ad unit size for bottom of destinations DFP ad

- app/assets/stylesheets/core/core_components/_pagination.sass
- app/data/styleguide/pagination_stubs.yml
- app/views/components/_pagination.html.haml
- app/views/styleguide/ui-components/pagination.html.haml
- spec/views/components/pagination_spec.rb
Replaced `first` & `last` buttons with actual numbers in order to let user know how much content he's dealing with. Added some ellipsis there :]
**ABOVE MV**
**BELOW MV**
> Bart tweak pagination

- app/assets/javascripts/lib/core/feature_detect.js
@stevebrownlee Can someone on your team take a look at this one?
I am seeing `no-3d-support` on the html element which is wrong since `translate3d()` has been available in Firefox for a while.
I've updated feature_detect.js to address this issue.
> Fix no-3d-support

- Gruntfile.js
- app/views/layouts/partials/inline_js/_a9.html
- app/views/layouts/partials/snippets/_head_js.haml
- vendor/assets/javascripts/amazon/a9.js
> Trello issue: https://trello.com/c/N6zvUvbv/3-implementation-of-a9-amazon-technology
For our AdOps team, we need to implement the ability for our DFP implementation to also call out to Amazon for bids on our ads.
1. Pull down related code for Gonzo (https://github.com/lonelyplanet/gonzo/pull/49)
2. Pull down this PR code
3. In Gonzo, point to local rizzo
4. Open the `a9_test` page
5. Verify in your Network tab traffic that there is a bid request sent to Amazon
> Implement Amazon script tags for whitelisted test page in Gonzo

- app/assets/javascripts/lib/core/ad_sizes.js
The new sizes are to support the Apple campaign headed our way.  The [1,1] sizes will allow the AdOps team to not show the MPU unit and bottom unit in Destinations and Homepage.
> Support Apple campaign ad sizes

- app/assets/javascripts/lib/core/ad_sizes.js
- app/assets/stylesheets/components/_stack.sass
Remove the 1001x300 size for the leaderboard slot since that's not what we're targeting.  Also making the MPU ad on the side rail have the same bgcolor as the body so that when it is set to 1x1, it's not obtrusive by having a different background color.
> More refined enhancements for Apple campaign

- app/assets/javascripts/lib/core/ad_sizes.js
Ensuring that the leaderboard, which we discovered is used on the homepage, can be minimized to 1x1
> Small leaderboard

- app/assets/stylesheets/core/layouts/modern/_ads.sass
Removing the padding media query for leaderboard ads for the duration of the Apple campaign so that the extra-wide ad remains centered as the browser size changes. JIRA ticket created to roll this back after the campaign. 
> JIRA ticket: https://lonelyplanet.atlassian.net/browse/LPMC-32
Note: this will be pushed to Homepage, and possibly Destinations, at 7pm tonight
1. Modify Waldorf to point to local Rizzo
2. Fire up Waldorf and visit localhost:8080/asia
3. Wait for the ads the load
4. Resize the browser and ensure that the ads always stays centered and does not get extra padding above 908px
> Remove 908px media query for ads

- app/assets/stylesheets/rizzo_next/_mixins.scss
Standardizes the look of the "see more" links found at the bottom of many DN/Bane components.
If you simply must see it in action, it is used in these PRs
Bane: https://github.com/lonelyplanet/bane/pull/78
Destinations: https://github.com/lonelyplanet/destinations-next/pull/159
> Add mixin for "see more" links

- app/assets/javascripts/app_core.js
- app/views/components/navigation/_breadcrumbs.html.haml
- vendor/assets/javascripts/polyfills/array_index_of.js
Remove old breadcrumbs as these were invalid and replace with new ones.
For reference:
https://developers.google.com/structured-data/breadcrumbs
Example output:
```
<div class="google-breadcrumbs is-hidden">
<div id="google-breadcrumb-0" itemprop="child" itemref="google-breadcrumb-1" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
<a href="http://www.lonelyplanet.com/thorntree" itemprop="url">
<span itemprop="title">
Thorn Tree
</span>
</a>
</div>
<div id="google-breadcrumb-1" itemprop="child" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
<a href="http://www.lonelyplanet.com//thorntree/categories/country-forums" itemprop="url">
<span itemprop="title">
Country forums
</span>
</a>
</div>
</div>
```
passes validation and produces valid output using: …
> Fix google breadcrumbs

- app/assets/javascripts/lib/analytics/travel_insurance_omniture.js
Don't run `trackView` on need-to-know views if they're already being tracked.
> Make sure Essential information is not double tracked

- app/assets/javascripts/lib/components/range_slider.js
Floor function on number in range [0,1] returns always 0 or 1 which is not valid max value for trips.
> Remove floor function from getMaxRangeValue method.

- README.md
- app/helpers/global_resources_helper.rb
- app/views/layouts/responsive.html.haml
Notification :point_down:  should show up if a cookie called `destinations_next_cookie` is set
> show notification to destinations-next alpha testers

- app/assets/stylesheets/rizzo_next/_base_mixins.scss
Fixes issue where an extra bottom border line was being drawn when tours component was not present. This universally removes any bottom border from a component that is the last one before the footer.
Addresses this card: https://lonelyplanet.atlassian.net/browse/DCV-289
> Remove border bottom from last  of type

- app/assets/stylesheets/components/_autocomplete.sass
- app/assets/stylesheets/core/_inputs.sass
This decreases CPU usage significantly (reported as a bug). Tried to replace it with something less demanding (-_-) but ended up deleting it. It wasn't of much use anyways - results are fetched before it's fully appeared. 
:fire: :fire: :fire:
> Remove loading indication from autocomplete

- app/assets/stylesheets/styleguide.sass
Fixed this:
for `car rentals`, `flights` & `travel insurance` widgets styleguide.
> Fixed datepicker dropdown hiding behind .wrapper

- app/views/components/forms/_radio_buttons_field.html.haml
- app/views/components/forms/_text_area.html.haml
fixes errors:
```
/app/views/components/forms/_radio_buttons_field.html.haml:4: warning: duplicated key at line 4 ignored: :data
/app/views/components/forms/_text_area.html.haml:2: warning: duplicated key at line 2 ignored: :data
```
these _warnings_ started showing in Rails 4.2.
I'm not sure anyone uses these features or where we could test the behaviour is correct? tests are passing...
@remybach can you have a look? :pray:
> remove duplicate :date attribute from form inputs

- app/assets/javascripts/app_core_for_gonzo.js
Ad_manager script from rizzo breaks the loading of js scripts in gonzo when the Adblock is turned on. There aren't any ads server in gonzo anyway, so we decided to create a special app_core for gonzo that doesn't require these two rizzo libraries.
> Create special app_core for gonzo without ad_manager and advertising lib

- app/assets/javascripts/lib/analytics/flights_omniture.js
`pageName` param in `flights_omniture` script shouldnt be overwritten when the` pageName` value is already present. This messed up statistics for flights widget in Essential Information
Jira ticket: https://lonelyplanet.atlassian.net/browse/LPMC-70
> Dont overwrite pageName when tracking flights widget click event

- app/assets/stylesheets/core/layouts/modern/_secondary_nav.sass
- app/views/components/navigation/_secondary.html.haml
It adds option to add custom title (html_safe) to be displayed instead of selected item. We'd like use it in Community to save some precious space. 
It's backwards compatible, won't blow anything anywhere up (I hope so :trolleybus:).
Before: 
After:
> Bart add custom title to secondary nav

- app/views/components/forms/_checkbox_field.html.haml
This adds .html_safe class to form labels.  Please check that html can be added in yml inputs and renders as such.
> adds html safe so form labels can include html

- app/assets/javascripts/app_core.js
- app/helpers/beta_helper.rb
- app/views/layouts/responsive.html.haml
You can test this PR by setting rizzo local in waldorf.
Then go to any destination page with `?beta=destinations-next` in the URL.
Verify after clicking the link in the banner that a cookie with `_v` set to `split-12-destinations-next` is correctly set.
> Working on code to add beta banner for Destinations Next

- app/helpers/js_helper.rb
- spec/helpers/js_helper_spec.rb
real source of `extend` function used (uglified in the source):
```
function extend (target, source) {
target = target || {};
for (var prop in source) {
if (typeof source[prop] === 'object') {
target[prop] = extend(target[prop], source[prop]);
} else {
target[prop] = source[prop];
}
}
return target;
}
```
> configure_js should merge objects instead overwriting.

- Gruntfile.js
- app/assets/javascripts/lib/core/user_feed.js
- app/assets/javascripts/lib/core/user_feed/content.js
- app/assets/javascripts/lib/core/user_feed/content/_shared.js
- app/assets/javascripts/lib/core/user_feed/content/activities.js
- app/assets/javascripts/lib/core/user_feed/content/messages.js
- app/assets/javascripts/lib/core/user_feed/fetcher.js
- app/assets/javascripts/lib/core/user_feed/flyout.js
- app/assets/javascripts/lib/core/user_feed/popups.js
- app/assets/javascripts/lib/core/user_feed/unread_counter.js
- app/assets/stylesheets/core/layouts/modern/_responsive_nav.sass
- app/assets/stylesheets/core/layouts/modern/_user_feed.sass
- app/data/layouts/user_nav.yml
- app/views/templates/global-nav/_user_signed_in.html.haml
- package.json
- spec/javascripts/fixtures/user_feed.html
- spec/javascripts/helpers/SpecHelper.js
- spec/javascripts/lib/core/user_feed_spec.js
**This PR is mainly for the "Your Feed Popups" feature.** 
The feature was requested by TT users, so it's disabled by default in all other apps. To enable it, you need to add `window.lp.userFeed.popups = true` property to your app.
All the other display settings are managed through TT [forum settings](https://www.lonelyplanet.com/thorntree/forums/settings) (will be available after [this](https://github.com/lonelyplanet/community/pull/2414) gets merged).
`Desktop`
`Mobile` (popup is full width and the close button is always visible)
**Note:**
Feed is fetched each 15 seconds, so it's extremely unlikely to get more than 1-2 notifications at once. Just wanted to show dat cool stacking animation :]
> Bart new feed popups

- app/helpers/beta_helper.rb
- spec/helpers/beta_helper_spec.rb
Rizzo was not correctly working on `Hotels` after it was bumped to
the latest version of Rizzo.  The error was an unitialized constant
of PlacePresenter because Hotels lacks such a presenter.  This
insulates that condition and wraps the module with tests to prevent
further problems.
> Apply Fixes to BetaHelper

- app/assets/javascripts/lib/core/user_feed/content.js
- app/helpers/js_helper.rb
- spec/helpers/js_helper_spec.rb
- spec/javascripts/fixtures/user_feed.html
- spec/javascripts/lib/core/user_feed_spec.js
full source of `extend`:
```
function extend (target, source) {
target = target || {};
for (var prop in source) {
if((typeof source[prop] === 'object') && source[prop] !== null && source[prop].constructor == Array){
target[prop] = source[prop];
} else if (typeof source[prop] === 'object') {
target[prop] = extend(target[prop], source[prop]);
} else {
target[prop] = source[prop];
}
}
return target;
}
```
handles arrays and null values properly.
Also define namespace key if it's empty before merging. So when merge happens the key is always present.
> Fix merge js

- Gruntfile.js
- app/assets/javascripts/lib/core/timeago.js
- app/views/layouts/partials/inline_js/_require_js_config.html.haml
- config/requirejs.yml
This prevents the necessity of updating requirejs config in each app.
> Bring back old timeago requirejs alias

- app/assets/javascripts/lib/core/user_feed/content.js
This fixes issue with catching wrong elements and redirecting to `undefault` bug.
> Fix wrong target on feed item click

- app/assets/stylesheets/sass/mixins/_responsive.sass
Proper `narrow-view` breakpoint value is `380px`
> Fix the wrong value of 'narrow-view' variable in documentation

- app/assets/stylesheets/core/core_components/cards/_variations.sass
This fixes issue when MPU card got squashed on devices with viewport width lower than 380px. 
JIRA ticket: https://lonelyplanet.atlassian.net/browse/LPMC-269
**Before**
**After**
This doesn't affect the cards behaviour on larger screens.
> Fix for squashed MPU card on mobile

- app/views/components/navigation/_nav_item.html.haml
- app/views/components/navigation/_submenu.html.haml
- app/views/layouts/partials/inline_js/_nativo.html
This one ads `data-lpa-` tracking attributes to submenus of core navigation items. Previously only primary nav items were taken into account. 
Pix for reference:
> Treat submenus of global navigation items as click-trackable.

- app/assets/javascripts/app_core.js
The prevent default needs to be higher up to make sure it gets cancelled before the location reload.
> Move prevent default

- app/helpers/js_helper.rb
Since we pass `ad_config`'s from all over the site to this single method, this might be the one place we can test for ads and decide to not show them in the context of acceptance tests. I sure hope so at least...
> Remove ads in tests

- app/helpers/js_helper.rb
This one prevents from initialising `AdManager` in testing environments.
> Don't load ads in test environment

- app/views/layouts/partials/inline_js/_nativo.html
As of 6 days ago when we put `async` on this, something odd started happening and a bunch of errors started randomly appearing...
I think what's happening is the Nativo script is also using a `umd` module for jQuery. When it loads async, it sometimes overwrites our own jquery and they happen to use a version of jQuery that does not support the `.wrap` method for whatever reason. Not to mention it's `2.1.1`.
Let's remove the async and see if the errors drop off.
> Remove async attribute

- app/helpers/beta_helper.rb
This fixes case when an app that uses rizzo has no `PlacePresenter` and no `ArticlesShowPresenter` defined.
> Make sure presenters are defined before using them in BetaHelper

- app/assets/javascripts/lib/page/controller.js
- spec/javascripts/lib/page/controller_spec.js
PROBLEM: So far empty params have been ALWAYS overwritten by current window.location.search. Probably that was a reason of introducing removePageParam here: https://github.com/lonelyplanet/rizzo/commit/cf3e10ceb2464819d4848272186b2e20de0a7483. Because of this, after closing lightbox page param diseappeared(problem spotted in community) while an other params were added to lightbox url. 
SOLUTION: Every time some state is pushed to local variable in _generateState both: url and params are provided and empty params are not overwritten by params from window.location(so, we respect that in some cases params do not exist).
Tested locally on community and gonzo.
/cc @WunderBart @drowka
> Manage url params in controller.js

- spec/javascripts/lib/components/gallery_spec.js
- spec/javascripts/lib/page/pushstate_spec.js
Change was forced after jasmine-core update to 2.4.0, more information: https://github.com/jasmine/jasmine/issues/948
----------------------
@WunderBart  @jcreamer898 can you take a look?
_I was also thinking about adding `expect(history.state).toEqual({});` but history.state is supported in phantomjs 2.0 and well it's additional thing to test. The most important is covered \o/_
> Tests for changes in history.state without using spies

- app/assets/javascripts/lib/page/controller.js
- spec/javascripts/lib/page/controller_spec.js
This one makes Controller send "page view" event to analytics tracker for each virtual page update  instead of relying on `dataLayer` and `lp.analytics.api.trackPageView`.
> Call trackEvent directly instead of tracking page view in Controller

- app/assets/javascripts/lib/analytics/flights.js
This is a tweak of params we send for tracking when user submits search form in Flights widget.
> Change flights widget's tracking event params

- app/assets/javascripts/lib/analytics/flights.js
- app/assets/javascripts/lib/analytics/travel_insurance_omniture.js
So, there was an error in the spec that slipped into codebase. `action` you see here fellas should be `label`. Yeeup.
> Switch label <-> action in event params for booking widgets

- lib/rizzo/assets.rb
- node_modules/rizzo-next/dist/rizzo-next.js
Rizzo Next needed to be updated to be included as a named module so that it wouldn't break when it actually ran in the browser. Also needed to add rizzo-next.css to the precompile so it gets deployed to s3.
> Add rizzo next to precompile, update to named AMD module

- app/controllers/rizzo/sailthru_controller.rb
- app/lib/rizzo/sailthru_service.rb
- app/views/layouts/partials/snippets/_footer_sitemap.html.haml
This change fixes `NameError (uninitialized constant Rizzo::SailthruController::SailthruService)`. Calling SailthruSevice from Rizzo::SailthruController was throwing NameError due to improper nesting (see. http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#nesting). I decided to use module nesting convention instead and it fixed the problem.
> namespace fix; form action path fix

- app/assets/stylesheets/core/layouts/modern/_primary_nav_new.sass
- app/views/layouts/custom/_head.html.haml
- app/views/layouts/custom/_post_header.html.haml
Because Rizzo Next uses rems and a base font size 10px and Rizzo uses a base font size of 14px, overrides needed to be added to make the header look the same across all areas of the site.
[View Codepen demo](http://codepen.io/thomasthesecond/pen/977f587e591f7d06d78f40f149bd6ad1)
> Make global header match Rizzo Next

- app/views/layouts/partials/snippets/_footer_sitemap.html.haml
This will also work for subdomains like shop.lonelyplanet.com.
> specify full url for newsletter submit endpoint

- app/assets/javascripts/lib/analytics/flights.js
- app/assets/javascripts/lib/analytics/travel_insurance_omniture.js
Booking widgets that lead off site (as a result of form submit) should be considered as "Partner Clicks" not "Partner Searches".
> Track flights and insurance submits as partner clicks

- Gruntfile.js
Prevent deleted scripts from being kept in public folder, causing build to fail.
> Add cleanJS to grunt ci task

- app/assets/javascripts/lib/components/datepicker.js
- spec/javascripts/fixtures/availability.html
- spec/javascripts/lib/components/datepicker_spec.js
+ If user selects end date first, start date calendar will now open automatically
+ Other Picker will now open each time user starts the selection process
+ Setting invalid date will reopen the other Picker now
+ Setting same date is now available via `allowSameDate` option (it's helpful in situations when used as
f.e. date range in search filters)
**note**: _everything is backwards compatible and doesn't require taking any actions to upgrade._
> Tweak datepicker.js

- app/assets/javascripts/lib/components/poi_map.js
request: https://github.com/lonelyplanet/rizzo/issues/1514
ToggleActive is self-instantiating component, calling its constructor directly will register active class toggling callback second time - that way clicking `.js-toggle-active` will have no effect, since it will fire callbacks twice (setting back original state)
> poi map resizing fix

- app/assets/javascripts/lib/core/advertising.js
- app/assets/stylesheets/core/layouts/modern/_ads.sass
- app/views/layouts/partials/snippets/_leaderboard.html.haml
This one adds pixel bait for adblockers. Checking for its visibility can detect some blockers which let `advertising.js` load.
Still, no match for µBlock (:heart:)
> Improve adblock check with pixel bait

- app/views/components/forms/_date_input.html.haml
Simple update for the datepicker to accept `min` and `max` properties.
```
= ui_component('forms/date_field', properties: { id: "text_id",
label: "Choose Date",
max: Date.today,
min: "2010-01-01",
name: "text_name",
})
```
> Datepicker accepts min and max props

- app/views/layouts/partials/inline_js/_a9.html
- app/views/layouts/partials/inline_js/_criteo.html
- app/views/layouts/partials/snippets/_head_js.haml
Due to problems with their implementation in Tealium (they introduced dependency on DFP; not added to Tealium yet).
> Bring back A9 and Criteo tags

- app/assets/javascripts/lib/widgets/flights_autocomplete.js
request: https://trello.com/c/EYctfZHq/188-flight-booking-tool-not-auto-filling-city-names
This widget used on https pages throws Mixed Content errors when requesting insecure (http) endpoint.
> fix mixed content

- app/assets/javascripts/lib/widgets/flights_autocomplete.js
request: https://trello.com/c/EYctfZHq/188-flight-booking-tool-not-auto-filling-city-names
Location autocomplete never worked (or stopped working some time ago) over https, I guess because skyscanner stopped supporting jsonp or new browsers introduced some more strict security policies - I don't really know.
Anyways, I think jsonp is not a good idea (executing third-party script on our side), besides that we were exposing our skyscanner private api key - definitely not a good idea. I decided to implement proxy endpoint in need-to-know: https://github.com/lonelyplanet/need-to-know/pull/391
dispatch p/r: https://github.com/lonelyplanet/dispatch/pull/663
> use new proxy endpoint for skyscanner autosuggest

- app/views/layouts/partials/snippets/_head_js.haml
This links legacy data objects used by Tealium and Omniture to `lp.dataLayer` global. 
`lp.dataLayer` will be prime data source for Google Tag Manager.
> Link legacy data layer objects to lp.dataLayer global

- app/assets/stylesheets/core/layouts/modern/_secondary_nav.sass
- app/assets/stylesheets/rizzo_next/_mixins.scss
- app/assets/stylesheets/sass/mixins/_utilities.sass
This should help close this issue in Waldorf
https://trello.com/c/rBFEX2NB/257-the-menu-overlays-are-appearing-underneath-the-ad-units-we-would-like-to-adjust-the-z-index-for-these-menu-s-so-that-it-it-not-a
> Add new z-index value and update row--secondary with new value

- app/assets/javascripts/lib/components/select_group_manager.js
Because we sometimes want to use select in Lightbox and it's not under `.js-wrapper`.
> Change default context for SelectGroupManager

- app/assets/stylesheets/components/_lightbox.sass
This will put the lightbox component above all ads that may have a
high z-index as well as above the secondary-nav component, which is
the component that the "above-ad" z-layer was originally created for
in #1593
Closes #1595
> Give lightbox "above-ad" z-layer

- app/lib/layout_support.rb
- features/global_resource.feature
Css is broken on shop over https: mixed content for app-core-legacy.css.
The same for lponline and contact-us - all those apps fetch header from http://rizzo.lonelyplanet.com/global-head.
> fix mixed content for app-core-legacy.css in legacy apps

- app/assets/stylesheets/components/_left_nav.sass
> Prevent left nav's active item border from adding padding

- app/views/layouts/partials/snippets/_footer_sitemap.html.haml
related to: https://github.com/lonelyplanet/gonzo/pull/342
We should always set default opt-in value (`true`) to avoid passing `on/off` string. More details: https://stackoverflow.com/questions/12911787/html-checkbox-default-value. Thanks @robuye for investigating this.
> fix: set default opt-in value

- app/assets/javascripts/lib/components/link_to.js
- spec/javascripts/fixtures/link_to.html
- spec/javascripts/lib/components/link_to_spec.js
It has other benefits, but I just needed it to support dynamically appended `data-link-to`s.
> Make LinkTo use single (context) listener

- Gemfile.lock
Announcement: [CVE-2018-3760](https://groups.google.com/forum/#!topic/ruby-security-ann/2S9Pwz2i16k)
> Update sprockets due to security vulnerability

- app/assets/javascripts/lib/components/availability_search.js
- app/assets/javascripts/lib/components/datepicker.js
- spec/javascripts/fixtures/availability.html
- spec/javascripts/lib/components/availability_search_spec.js
Solves the bug that dates are not picked up from the 'value' and prepopulated at page reload.
Example: https://www.lonelyplanet.com/thorntree/travel_companions
> Set default dates from the 'value' html attr

- README.md
- app/views/layouts/custom/_header.html.haml
- app/views/layouts/custom/_post_header.html.haml
- app/views/layouts/custom/preview.html.haml
- app/views/layouts/responsive.html.haml
This code adds the new global header to rizzo. To use it, apps will have to pass in `global_header: true`. The global header theme can also be passed in as `global_header_theme: "white"`.
> Add global header ssi code to rizzo

- app/controllers/layout_controller.rb
- app/lib/layout_support.rb
- app/views/layouts/custom/_head.html.haml
- app/views/layouts/custom/preview.html.haml
- app/views/layouts/minimal.html.haml
- app/views/layouts/partials/snippets/_head_js.haml
- app/views/layouts/responsive.html.haml
- app/views/layouts/styleguide.html.haml
I'd rather add this in consistently in each repo, so need a way to make `rizzo` omit it from the `global_head` route.
> [ADS-149] feat: create query param for omitting gtm.js snippet from global_head
