lonelyplanet/rizzo

app/assets/javascripts/lib/core/timeago.js, app/assets/javascripts/lib/core/user_feed.js, spec/javascripts/fixtures/timeago.html, spec/javascripts/lib/core/timeago_spec.js, spec/javascripts/lib/core/user_feed_spec.js
There's a problem in Community where `timeago` randomly simply doesn't init at all (mostly on first visit to random threads). The worst part is that it doesn't leave any error trace whatsoever. Thought it was `require.js`-specific but couldn't find any culprit there.
This is the first (and hopefully final) step to make `timeago` work properly each time.
=> Bart fix timeago

app/assets/javascripts/lib/components/poi_list.js
=> change dot to marker.

app/assets/stylesheets/components/_read_more.sass
=> Fix read less bug

app/assets/javascripts/lib/components/datepicker.js, app/assets/javascripts/lib/widgets/car_rental.js, app/assets/javascripts/lib/widgets/flights.js, app/assets/javascripts/styleguide.js, app/views/layouts/partials/inline_js/_require_js_config.html.haml, config/requirejs.yml, spec/javascripts/helpers/SpecHelper.js
In Community (development), this script error is rather constant than random: 
Putting `picker` components in `requirejs` config seems to fix the issue. Console is clean :clap:
=> Fixed picker.js throwing random requirejs script error on development

app/views/layouts/partials/inline_js/_social_remarketing.html, app/views/layouts/partials/snippets/_footer_js.html.haml
Related trello card here: https://trello.com/c/ZHyx0sW6
=> Add social remarketing tags

app/assets/stylesheets/core/_grid.sass, app/assets/stylesheets/core/_inputs.sass, app/assets/stylesheets/core/core_components/_accordion.sass, app/assets/stylesheets/core/core_components/_pagination.sass, app/assets/stylesheets/core/core_components/_place_title.sass, app/assets/stylesheets/core/layouts/legacy/_overrides.sass, app/assets/stylesheets/core/layouts/modern/_breadcrumbs.sass, app/assets/stylesheets/core/layouts/modern/_footer.sass, app/assets/stylesheets/core/layouts/modern/_nav_flyout.sass, app/assets/stylesheets/core/layouts/modern/_secondary_nav.sass, app/assets/stylesheets/core/layouts/modern/_shopping_cart.sass, app/assets/stylesheets/core/utilities/_responsive.sass, app/assets/stylesheets/styleguide.sass, app/controllers/styleguide_controller.rb, app/views/components/navigation/_secondary.html.haml, app/views/layouts/partials/snippets/_footer_sitemap.html.haml, app/views/layouts/partials/snippets/_primary_navigation_bar.html.haml, app/views/layouts/styleguide.html.haml
Removes the .responsive flag from (almost) everything under `/stylesheets/core`.
This basically means secondary nav and footer need checking
=> If remove responsive core

app/data/styleguide/cards_stubs.yml, app/views/components/cards/_card.html.haml
Check this request in conjunction with: https://github.com/lonelyplanet/landing-pages/pull/319
=> Adds  :target:  "_blank" to UI components 

app/docs/general/development-principles.md, app/docs/general/front-end-security.md
I read your documentation tonight and found these two tiny typos.
=> Fixing tiny typos

npm-shrinkwrap.json, package.json
https://trello.com/c/MzRvYm2i/199-add-an-npm-shrinkwrap-file
=> add npm shrinkwrap

app/assets/javascripts/lib/components/gallery.js, app/assets/javascripts/lib/components/slider.js, app/assets/stylesheets/components/_gallery.sass, app/assets/stylesheets/sass/mixins/_responsive.sass, app/views/layouts/partials/inline_js/_social_remarketing.html
https://trello.com/c/R9iWiP01/603-images-are-still-being-stretched-at-larger-screen-sizes-in-the-image-gallery
=> Fix the image stretchy by using percentage 4 width

app/assets/stylesheets/widgets/_travel_insurance.sass, app/views/layouts/partials/inline_js/_social_remarketing.html
Thanks to @chee for the clever `onload` solution.
=> Fix twttr issue and travel insurance z-index

app/views/layouts/partials/inline_js/_require_js_config.html.haml, bower.json, vendor/assets/javascripts/jquery-bbq-deparam/jquery-deparam.js
We're not going to be updating deparam, wrapShim on requirejs works only intermittently, this requires no config for any other apps. Any objections?
=> Wrap deparam in require

app/assets/stylesheets/core/layouts/modern/_nav_flyout.sass, app/assets/stylesheets/core/layouts/modern/_primary_nav.sass
and repair the handle of the shopping bag
https://trello.com/c/wJHTdRnT/673-in-the-drop-down-menu-under-a-city-the-icon-for-activities-under-things-to-do-we-use-is-the-running-man-but-isis-has-got-to-him
=> Rehead the activities man

app/views/components/_hero_banner.html.haml
cukes
```
20 scenarios (20 passed)
61 steps (61 passed)
0m1.213s
```
specs
```
Finished in 0.74282 seconds
168 examples, 0 failures
```
=> allow unescaped HTML in hero-banner content

app/views/components/navigation/_nav_item_tmpl.html.haml, app/views/layouts/custom/preview.html.haml, app/views/layouts/partials/inline_js/_krux.html, app/views/layouts/responsive.html.haml, app/views/layouts/styleguide.html.haml, app/views/styleguide/partials/_shared.html.haml
Ran rizzo through some HTML validation and did a tad of clean-up. Would love some :eyes: on it. Especially anybody dealing w/mustache templates, if that will screw with you at all. Also an unnecessary charset on a script tag surrounding the DFP stuff.
=> Bt validations

app/views/components/forms/_text_input.html.haml
We need these in Community.
Someone else might need em too. 
Good to have em :]
=> Added autofocus & autocomplete attributes to text input

app/assets/javascripts/lib/core/nav_search.js
adding in tracking for autocomplete search results.
=> added tracking to search autocomplete

app/views/components/navigation/_nav_item_tmpl.html.haml, app/views/layouts/partials/snippets/_primary_navigation_bar.html.haml, app/views/layouts/responsive.html.haml, app/views/layouts/styleguide.html.haml, app/views/styleguide/js-components/template.html.haml, app/views/styleguide/partials/_shared.html.haml
one small step for sed, a normal person foot sized step for rfc2045 being satisfied.
as it was being broken for no good reason.
=> rfc 2045 reborn

app/assets/javascripts/lib/styleguide/anchor_target.js, app/assets/javascripts/lib/styleguide/colours.js, app/assets/javascripts/lib/styleguide/svg.js, app/assets/javascripts/styleguide.js, app/views/styleguide/partials/_colour_finder.html.haml, app/views/styleguide/partials/_svg_filter.html.haml
for the styleguide so you can link to specific colours and icons. any whatever else might have a text filter some day
=> anchor target

app/assets/javascripts/lib/components/poi_map.js
Please check by,
1. Loading up a map on somewhere like hotels
2. Move mouse or click in static map
3. Ensure that map is created correctly with all POIs
4. Ensure subsequent clicks do not attempt to continually recreate the map
=> Maps were being loaded any click or mouseover

app/assets/javascripts/lib/components/page_hopper.js, app/assets/javascripts/lib/core/nav_search.js, app/assets/javascripts/lib/widgets/car_rental.js, app/assets/javascripts/lib/widgets/flights_autocomplete.js, app/assets/stylesheets/components/_autocomplete.sass, app/assets/stylesheets/components/_page_hopper.sass, app/assets/stylesheets/core/_inputs.sass, app/assets/stylesheets/widgets/_booking.sass, app/assets/stylesheets/widgets/_car_rental.sass, app/assets/stylesheets/widgets/_flights.sass, app/views/styleguide/js-components/autocomplete.html.haml, bower.json, vendor/assets/javascripts/autocomplete/.bower.json, vendor/assets/javascripts/autocomplete/bower.json, vendor/assets/javascripts/autocomplete/dist/autocomplete.js
=> Bart update autocomplete styles

app/assets/javascripts/lib/widgets/car_rental.js
https://trello.com/c/gSe42kdj/337-remove-autofill-of-home-country-for-car-rental
=> Remove country selection based on user currency.

app/docs/js/code-style.md
Adding in rules for working with ES2015. This is totally up for any collaboration.
=> Updating style guide for es2015 rules

app/assets/stylesheets/core/layouts/modern/_ads.sass
> Related Waldorf PR: https://github.com/lonelyplanet/waldorf/pull/1844
Adding new style for DFP ad to be served at bottom of destination pages - which replaces the existing AdSense display
=> New style for bottom DFP ads

app/assets/javascripts/lib/utils/image_preloader.js
=> Fix failing build because there was an extra space in JavaScript.

app/assets/stylesheets/components/_autocomplete.sass, app/assets/stylesheets/widgets/_car_rental.sass, bower.json, vendor/assets/javascripts/autocomplete/bower.json, vendor/assets/javascripts/autocomplete/dist/autocomplete.js
This also fixes broken primary nav search results clicking.
=> Bart bump autocomplete

.npmignore, app/assets/stylesheets/rizzo_next/_clearfix.scss, app/assets/stylesheets/rizzo_next/_color_variables.scss, app/assets/stylesheets/rizzo_next/_font_variables.scss, app/assets/stylesheets/rizzo_next/_fonts.sass, app/assets/stylesheets/rizzo_next/_icons.scss, app/assets/stylesheets/rizzo_next/_mixins.scss, app/assets/stylesheets/rizzo_next/_reset.sass, app/assets/stylesheets/rizzo_next/_utility_classes.scss, app/assets/stylesheets/rizzo_next/_webpack_deps.scss, app/assets/stylesheets/rizzo_next/core.scss, app/assets/stylesheets/sass/mixins/_responsive.sass, app/views/layouts/partials/snippets/_doctype_declaration.html.haml
This simply adds a new folder to rizzo for destinations next, no existing code is modified. Also an npmignore added.
=> Add in styleguide, and core for destinations pages

.jscs.json, Gruntfile.js, package.json
Update fonts, create pre-install script to grab them
=> Fix issue with jscs, add submodule update to npm

app/assets/stylesheets/core/core_components/_pagination.sass, app/data/styleguide/pagination_stubs.yml, app/views/components/_pagination.html.haml, app/views/styleguide/ui-components/pagination.html.haml, spec/views/components/pagination_spec.rb
restore pagination tweaks (after force push?)
=> Bart tweak pagination

app/views/layouts/custom/_footer.html.haml
Very similar to #1273, just removes the footer when not needed.
=> added no_footer var for external sites

app/views/components/navigation/_nav_item.html.haml
@WunderBart what do you think?
=> Adding a possibility to create links with set target in nav items

app/assets/stylesheets/rizzo_next/_fonts.sass, package.json
=> Actually fix font paths and bump package.json

app/assets/stylesheets/rizzo_next/_color_variables.scss, app/assets/stylesheets/rizzo_next/_icons.scss, app/assets/stylesheets/rizzo_next/_mixins.scss
Adds styles to rizzo next to make search specific colors and icons in destinaions-next.
Related PRs: 
https://github.com/lonelyplanet/bane/pull/28
https://github.com/lonelyplanet/destinations-next/pull/97
=> add styles for search

app/assets/stylesheets/rizzo_next/_buttons.scss, app/assets/stylesheets/rizzo_next/_color_variables.scss, app/assets/stylesheets/rizzo_next/_font_variables.scss, app/assets/stylesheets/rizzo_next/_icons.scss, app/assets/stylesheets/rizzo_next/_mixins.scss, app/assets/stylesheets/rizzo_next/_text_mixins.scss
This adds necessary mixins and classes for articles widget
ALSO fixes the need for a window.load event on text clamping!
=> Support for articles widget

app/assets/stylesheets/rizzo_next/_icons_mixins.scss, app/assets/stylesheets/rizzo_next/_webpack_deps.scss
> Bane PR: https://github.com/lonelyplanet/bane/pull/64
Adding a mixin for adding type icons for the Destinations Next search control
=> Icons mixin

app/assets/stylesheets/rizzo_next/_buttons.scss, app/assets/stylesheets/rizzo_next/_headings.scss, app/assets/stylesheets/rizzo_next/_mixins.scss, app/assets/stylesheets/rizzo_next/_text_mixins.scss, app/assets/stylesheets/rizzo_next/core.scss
Heading-2 now is no longer a mixin, but changes it's properties at the same breakpoints regardless of it's component. 
Many other mixins updated to be more responsive and accurate to destinations next PSD
=> Update mixins and remove some spacing where it didn't belong

app/assets/javascripts/lib/core/ad_sizes.js
=> Updating the new ad size for the Apple campaign from 970x300 to 1000x300

app/assets/stylesheets/components/_left_nav.sass
=> border-radius fix for left nav items

app/assets/stylesheets/rizzo_next/_buttons.scss
=> update button style

app/assets/javascripts/lib/core/nav_search.js
Returning autocomplete results to flamsteed when user successfully selects an item in the autocomplete.
=> add logs to autocomplete

app/views/layouts/partials/inline_js/_criteo.html
Title says it all. Script comes directly from Criteo integration guide.
1. Visit http://assets.lonelyplanet.com/YXBwbGVfdGVzdA==.html
2. Verify that page loads correctly
3. Verify that there is a call to `rta.js`
=> Adding target script that enables Criteo to receive the correct DFP tag values

app/views/layouts/partials/inline_js/_criteo.html
Adding in additional code from Criteo team that adds the googletag mechanism that will stop errors from happening on bids
=> More Criteo code to establish googletag 

app/assets/stylesheets/core/_inputs.sass, app/data/styleguide/forms_stubs.yml, app/views/components/forms/_select_multiple.html.haml, app/views/components/forms/_select_multiple_field.html.haml
=> Add select multiple component

vendor/assets/javascripts/flamsteed/lib/javascripts/flamsteed.js
=> make flamsteed web pack friendly

app/assets/javascripts/lib/core/ad_manager.js, app/assets/stylesheets/core/layouts/modern/_ads.sass, vendor/assets/javascripts/jquery.dfp.js/jquery.dfp.js
This is a small workaround that will prevent showing up ad placeholder before it's loaded. This needs to be part of more solid solution (I'm working on it).
=> Tk fixing adds

app/assets/javascripts/lib/core/ad_manager.js, app/assets/stylesheets/core/layouts/modern/_ads.sass, vendor/assets/javascripts/jquery.dfp.js/jquery.dfp.js
This seems to cause problems on community. I guess SSL conflict there renders this "solution" faulty.
=> Revert of the ads quick fix

app/assets/javascripts/lib/components/gallery.js
https://lonelyplanet.atlassian.net/browse/LPMC-66
=> Add updating source field in gallery component

app/views/layouts/partials/snippets/_head_js.haml
Exposes `window.lp.analytics.utag_data`
=> Tk add utag

app/views/layouts/partials/inline_js/_nativo.html, app/views/layouts/partials/snippets/_head_js.haml
This adds nativo snippet to `head_js.haml`.
=> Add nativo.

app/assets/javascripts/lib/components/datepicker.js, app/assets/stylesheets/components/_datepicker.sass, spec/javascripts/lib/components/datepicker_spec.js
=> Moar Datepicker tweaks

app/helpers/beta_helper.rb
This will allow us to deploy this code without launching so we can do some testing.
=> Set banner logic to false until we're ready

app/helpers/js_helper.rb, spec/helpers/js_helper_spec.rb
Reverts lonelyplanet/rizzo#1375
does not work when key is not set.
=> Revert "configure_js should merge objects instead overwriting."

Gruntfile.js, app/assets/javascripts/lib/core/timeago.js, app/assets/javascripts/lib/core/user_feed/content.js, app/views/layouts/partials/inline_js/_require_js_config.html.haml, config/requirejs.yml, spec/javascripts/lib/core/timeago_spec.js, vendor/assets/javascripts/jquery-timeago/jquery.timeago.js
Should fix annoying memory leak causing mad CPU heat caused by stacking intervals on nodes that are no longer in DOM.
ref: https://github.com/rmm5t/jquery-timeago/commit/b5a364d3a24b4e69aaec2005e32649a494eed826
=> Bump jquery-timeago to v1.4.3

app/assets/stylesheets/core/layouts/modern/_primary_nav.sass
From ![screenshot 2015-10-22 12 30 30](https://cloud.githubusercontent.com/assets/1451471/10663034/bbc45a94-78b8-11e5-90bd-e737d67ab479.png) to ![screenshot 2015-10-22 12 30 09](https://cloud.githubusercontent.com/assets/1451471/10663035/bbc46052-78b8-11e5-9115-434eed0063d6.png)
=> Fix JOIN button position in main nav

app/assets/stylesheets/components/_alerts.sass, app/views/layouts/responsive.html.haml
Updates alert styling to use custom background and text alignment specific to the beta test opt-in/out alert
=> Change Destinations Next beta opt-in/out banner styling

app/helpers/footer_helper.rb
https://lonelyplanet.atlassian.net/browse/LPMC-255
=> [LPMC-255] update footer

app/helpers/beta_helper.rb
=> Go live w/ the banner for beta

app/assets/javascripts/app_core.js, app/helpers/beta_helper.rb
Trying to reach a statistical significance a bit faster.
=> Up the percentage for showing the banner

app/assets/javascripts/app_core.js, app/helpers/beta_helper.rb, app/views/layouts/responsive.html.haml
Going to show the beta banner w/ JavaScript now instead of Ruby because of caching issues.
=> Beta banner load w/ JavaScript

app/assets/javascripts/app_core.js, app/helpers/beta_helper.rb, app/views/layouts/responsive.html.haml, spec/helpers/beta_helper_spec.rb
Need to make sure the template is actually on the page.
=> Make sure banner is on the page before appending to DOM

app/assets/javascripts/app_core.js, app/assets/stylesheets/components/_alerts.sass
Upping the percentage of people seeing the banner.
Hoping to draw eyes w/ green color.
=> Change banner color, up percentage

app/assets/javascripts/app_core.js, app/assets/stylesheets/components/_alerts.sass, app/views/layouts/responsive.html.haml
We're really trying to make this banner stand out a bit more. Very very little engagement so far.
=> Making the beta banner stand out a bit more

app/data/layouts/primary_nav.yml, app/data/styleguide/title_stubs.yml
This one brings working slug for "Antarctica" place. 
Related: https://github.com/lonelyplanet/destinations-next/pull/434
=> Use working 'antarctica' slug

app/assets/javascripts/app_core.js, app/assets/javascripts/lib/core/newsletter_form.js, app/views/layouts/partials/snippets/_footer_sitemap.html.haml, spec/javascripts/fixtures/newsletter_form.html, spec/javascripts/lib/core/newsletter_form_spec.js
Newsletter endpoint changed (reimplemented from scratch in gonzo) and footer form in rizzo stopped working. New endpoint responds with http status codes and this component is responsible for handling these responses after submitting the form.
https://lonelyplanet.atlassian.net/browse/LPMC-302
=> Mk newsletter form component

app/assets/javascripts/lib/core/user_feed.js, app/assets/javascripts/lib/core/user_feed/content.js, app/assets/javascripts/lib/core/user_feed/content/_shared.js, app/assets/javascripts/lib/core/user_feed/content/activities.js, app/assets/javascripts/lib/core/user_feed/content/messages.js, app/assets/javascripts/lib/core/user_feed/popups.js, app/assets/javascripts/lib/core/user_feed/slide_in.js, app/assets/stylesheets/core/layouts/modern/_user_feed.sass, spec/javascripts/fixtures/user_feed.html, spec/javascripts/lib/core/user_feed_spec.js
- new feed indication changed to red background instead of blue stripe
- unread content is now localStored until feed is open & closed
- unread PMs indication works same as the activities one
- closing slide-in on mobiles is now done by tapping anywhere outside
- click behaviour replaced with hover on desktops
=> Slide-in feed bug fixes & improvements

app/assets/javascripts/lib/analytics/travel_insurance_omniture.js
This one adds GA tracking for World Nomads widget we use on "Essential Information" and "Travel Insurance" pages.
=> Track world nomads widget with GA

app/data/layouts/user_nav.yml, app/views/templates/global-nav/_user_signed_in.html.haml
Route has been changed, old link doesn't work anymore
=> Update PMs link in nav

.gitignore, node_modules/rizzo-next/dist/common.js, node_modules/rizzo-next/dist/header.html, node_modules/rizzo-next/dist/rizzo-next-build.js, node_modules/rizzo-next/dist/rizzo-next.css, node_modules/rizzo-next/dist/rizzo-next.js, node_modules/rizzo-next/dist/search.html, package.json
When gems get copied down they exclude what's in the gitignore so rizzo next was getting left out.
=> Including rizzo next npm dist folder

app/assets/javascripts/app_core.js, app/views/layouts/custom/_post_header.html.haml, config/application.rb, lib/rizzo/engine.rb
I think the problem was there were a bunch of files making into the asset path from other `node_modules`. Adding only what's needed seems to help.
=> Adding only the dist folder to the paths

app/assets/javascripts/lib/analytics/car_rental.js
This one makes car rental forms that appear aside on some NTK pages pass Tealium requirements.
=> Simplify tracking params of car-rental widget

node_modules/rizzo-next/dist/rizzo-next.js
=> Updating rizzo next

config/environments/production.rb
Requires https://github.com/lonelyplanet/chef-repo/pull/1801 first.
=> Use proper path for log file

app/helpers/beta_helper.rb, app/views/layouts/responsive.html.haml
No reason to have these now that we're moving to 1%.
=> Removing beta banners

app/controllers/layout_controller.rb, app/helpers/beta_helper.rb, spec/controllers/layout_controller_spec.rb
This query param works only for layouts endpoint.
/cc @gnisanci @jcreamer898
=> Allow Shop to fetch new nav bar using query param instead of a cookie

node_modules/rizzo-next/dist/header.html, node_modules/rizzo-next/dist/rizzo-next.css, node_modules/rizzo-next/dist/rizzo-next.js, node_modules/rizzo-next/dist/search.html
Making sure the new header is updated.
=> Updating to the latest rizzo next header

app/assets/javascripts/app_core.js, app/helpers/beta_helper.rb, node_modules/rizzo-next/dist/rizzo-next.css, node_modules/rizzo-next/dist/rizzo-next.js
Pulling in change from most recent RN.
Had to rename the cookie check for global nav. Dispatch adds an underscore to it.
=> Bump Rizzo Next

app/assets/javascripts/app_core_legacy.js
Load sailthru form handling js in app_core_legacy (for apps like shop).
=> load sailthru form in app_core_legacy

app/assets/javascripts/lib/core/ad_manager.js, spec/javascripts/lib/core/ad_manager_spec.js
Not sure why, but interest was never sent to DFP for targeting...
=> Add interest to dfp targeting

app/assets/javascripts/lib/core/cookie_compliance.js
This is the result of a miss from switching from CS to JS.
Missed a return. ಠ_ಠ
=> Fix cookie compliance

app/assets/javascripts/lib/analytics/flights.js, app/assets/javascripts/lib/analytics/travel_insurance_omniture.js, app/assets/javascripts/lib/page/controller.js, app/views/components/navigation/_nav_item.html.haml
This one tweaks format of tracking events that report user activity on booking widgets.
=> Change tracking events format

app/assets/javascripts/lib/widgets/flights.js
details: https://github.com/lonelyplanet/rizzo/issues/1494
=> [#1494] update skyscanner url generation

app/views/components/widgets/_flights.html.haml
details: https://github.com/lonelyplanet/rizzo/issues/1494
related p/r: https://github.com/lonelyplanet/need-to-know/pull/365
=> flights widget fix (prepopulate with airport code also)

app/assets/javascripts/lib/analytics/analytics.js, app/assets/javascripts/lib/page/controller.js, spec/javascripts/lib/page/controller_spec.js
This one handles page view tracking in appropriate place and ensures event is sent after lightbox renders its content with new datalayer.
=> Track pageView after lightbox content is ready

app/views/layouts/partials/inline_js/_a9.html
Removes Amazon Associates tag.
**Do not merge before Tealium deploy.**
=> Rm Amazon A9 tag

app/assets/javascripts/app_core_legacy.js
This change got missed when removing the split.
=> Make the header load on shop

node_modules/rizzo-next/dist/header.html, package.json
Shop was breaking because of the `shop` subdomain.
=> Update header w/ absolute links

app/views/layouts/partials/inline_js/_krux.html
Remove Krux for Tealium  tag management.
**Do not merge before Tealium tag deployment.**
=> Rm krux tag snippet

app/assets/stylesheets/core/core_components/_forms.sass, app/views/components/forms/_checkbox_field.html.haml
=> Handle disabled option in checkbox

node_modules/rizzo-next/dist/header.html, package.json
Reverts lonelyplanet/rizzo#1538
We need it for Shop to make it work
@WunderBart  @jcreamer898
=> Revert "update to rizzo-next for featured subnav"

app/data/layouts/primary_nav.yml
Reverts lonelyplanet/rizzo#1539
=> Revert "updating featured subnav for old menus"

node_modules/rizzo-next/dist/rizzo-next.js, package.json
This will get the new notification link live for the shop cart.
=> Bump rizzo for new notification link

node_modules/rizzo-next/dist/rizzo-next.js, package.json
=> Update rizzo-next for shop link in nav

node_modules/rizzo-next/dist/rizzo-next.js, package.json
more info: https://github.com/lonelyplanet/rizzo-next/pull/551
=> bump rizzo-next

app/views/layouts/partials/inline_js/_recaptcha.html.haml, app/views/layouts/partials/snippets/_head_js.haml
We are going to add google noCaptcha reCaptcha verification to all newsletter forms. We will need this script in head. 
more info on reCaptcha: https://developers.google.com/recaptcha/docs/display
related requests: https://trello.com/c/YrE6YQbQ/32-bit2017-website-live-10-25-3am-cst, https://trello.com/c/8zEmNQjI/1690-lp-kids-newsletter-sign-up-validation-recapture, https://trello.com/c/TjwuALt4/1689-newsletter-sign-up-validation-recapture
=> render recaptcha script

node_modules/rizzo-next/dist/header.html, node_modules/rizzo-next/dist/rizzo-next.js, package.json
=> Am update nav bit

app/views/layouts/partials/snippets/_head_js.haml
Needed for migration period from Tealium to Google Tag Manager.
=> Link UDO to lp.analytics

package.json
=> Lock rizzo-next version to prevent accidental update

app/controllers/documentation_controller.rb, app/controllers/performance_controller.rb, app/controllers/styleguide_controller.rb
@wunderbart, I will need it for Rails 5 upgrade in community
=> Replacing before_filter with before_action s it is deprecated in Rails 5

app/views/layouts/partials/snippets/_footer_sitemap.html.haml
request: https://trello.com/c/OTWmUGWj/168-hyperlinking-newsletter-in-lp-footer
We want to link to /newsletter in footer.
=> link to /newsletter in footer

app/controllers/documentation_controller.rb, app/controllers/performance_controller.rb, app/controllers/styleguide_controller.rb
Reverts lonelyplanet/rizzo#1577
=> Revert "Replacing before_filter with before_action s it is deprecated in Rails 5"

app/assets/javascripts/lib/core/ad_manager.js
@robuye @gnisanci 
This fixes the `dfp is not a function` error.
=> Fix dfp dependency error

app/controllers/documentation_controller.rb, app/controllers/performance_controller.rb, app/controllers/styleguide_controller.rb
=> Update semantics to kill deprecation warnings

app/assets/javascripts/app_core.js, app/assets/javascripts/app_core_for_gonzo.js
Because window.s = s_code = omniture.
@robuye / @tkali
=> Remove code dependent on window.s

app/assets/stylesheets/core/_inputs.sass, app/views/layouts/partials/snippets/_footer_sitemap.html.haml
high priority legal request, more details: https://trello.com/c/EbZKffod/349-add-extra-opt-in-to-newsletter-per-legal
=> add opt-in to newsletter form

app/helpers/footer_helper.rb
request: https://github.com/lonelyplanet/rizzo/issues/1616
=> add tourism solutions to the header; remove all social icons but fb, tw and pinterest

app/assets/javascripts/lib/utils/throttle.js
throttle.js should fire throttled func on start
=> Make throttle.js more throttle & less debounce

app/lib/layout_support.rb, features/global_resource.feature
request: https://github.com/lonelyplanet/shop/issues/23
similar issue: https://github.com/lonelyplanet/rizzo/pull/1620 (I forgot to set it for responsive pages)
=> fix mixed content for app-core-legacy.css in legacy apps (responsive)

app/assets/stylesheets/core/layouts/modern/_primary_nav_new.sass
request: https://github.com/lonelyplanet/rizzo/issues/1642#issuecomment-339664847
=> fix avatar

app/helpers/footer_helper.rb, lib/rizzo/url_validator.rb, spec/lib/url_validator_spec.rb
request: https://github.com/lonelyplanet/rizzo/issues/1640
=> use declared schema if available

app/assets/stylesheets/core/_inputs.sass, app/views/layouts/partials/snippets/_footer_sitemap.html.haml
request: https://github.com/lonelyplanet/rizzo/issues/1650
=> update footer newsletter

app/helpers/footer_helper.rb, app/views/layouts/partials/snippets/_footer_sitemap.html.haml
request: https://lonelyplanet.atlassian.net/browse/DOT-166
=> update footer links

app/assets/javascripts/lib/widgets/travel_insurance.js, app/assets/stylesheets/core/core_components/_badges.sass, app/assets/stylesheets/widgets/_travel_insurance.sass, app/views/components/navigation/_left_nav_item.html.haml, spec/javascripts/fixtures/travel_insurance.html, spec/javascripts/lib/widgets/travel_insurance_spec.js
Needed for https://github.com/lonelyplanet/community/pull/3337
=> Tweak world nomads widget

app/views/layouts/custom/_header.html.haml, app/views/layouts/custom/_post_header.html.haml, app/views/layouts/custom/preview.html.haml, app/views/layouts/responsive.html.haml
This updates the global header SSI comment to include the global header version option.
=> Add the option to pass in a version to the global header

app/assets/javascripts/lib/core/sailthru_form.js
_tracking_
_tracking_
_tracking_
=> feat: track newsletter subscriptions

app/helpers/footer_helper.rb, app/views/components/footer.html
jira: https://lonelyplanet.atlassian.net/browse/CMS-213
=> [CMS-213] remove travel companions link from footer

bower.json, vendor/assets/javascripts/jquery.dfp.js/jquery.dfp.js
Firefox's content blocking is causing dfp to throw errors when it's trying to execute gtm commands ("setTargeting is undefined"). It breaks other scripts when thrown. This update seems to be fixing it :boom:
=> Bump jquery.dfp.js to v2.4.2

README.md, app/helpers/footer_helper.rb, app/views/layouts/partials/snippets/_footer_sitemap.html.haml
Updated documentation to not reference gonzo because the newsletter route doesn't support GET anymore. Can simply
test changes locally.
Changed footer links to be more like our current ones in DFE.
=> Footer updates and documentation
